#!/bin/bash

#WGP_SCRIPT=$WGP_EXPERIMENT_DIR/local/$WGP_EXPERIMENT_SCRIPT
#echo "Running: "$WGP_SCRIPT
#echo "Hostname: "$HOSTNAME

parallel -k \
-a foo/param-input.txt \
--colsep ' ' \
--no-notice \
--sshloginfile foo/sshlogins.txt \
--env WGP_EXPERIMENT_DIR \
--results results \
'./foo/weka-j48-2params.sh {1} {2} {3}'
