#!/bin/bash

WGP_EXPERIMENT_DIR=$1

if [ -z $WGP_EXPERIMENT_DIR ]; then
	echo "You must specify a directory to copy to the remote machine."
	echo "E.g. wgp-copyfiles foo"
	exit 1
fi

if [ -z $WGP_REMOTE_NAME ]; then
	echo "You must specify the name of the remote machine to copy the directory to."
	echo "Have you sourced env.sh in your experiment folder?"
	exit 1
fi

# Copies experimental directory to remote directory.

echo "Copying directory: "$WGP_EXPERIMENT_DIR
echo "To: "$WGP_REMOTE_NAME:$WGP_EXPERIMENT_DIR

#scp -r $WGP_EXPERIMENT_DIR $WGP_REMOTE_NAME:

# make sure the directory exists first!
# mkdir will do nothing if the directory already exists
ssh $WGP_REMOTE_NAME mkdir -p $WGP_EXPERIMENT_DIR

# recursive, update, and verbose
rsync -ruv $WGP_EXPERIMENT_DIR/* $WGP_REMOTE_NAME:$WGP_EXPERIMENT_DIR