#!/bin/bash

WPG_EXPERIMENT_DIR=$1

if [ -z $WGP_EXPERIMENT_DIR ] || [ -z $WGP_REMOTE_NAME ]; then
	echo "Have you sourced your project's env.sh file?"
	exit 1
fi

# Copies experimental directory to remote directory.

echo "Copying directory: "$WGP_EXPERIMENT_DIR
echo "To: "$WGP_REMOTE_NAME:$WGP_EXPERIMENT_DIR

scp -r $WGP_EXPERIMENT_DIR $WGP_REMOTE_NAME:
