#!/bin/bash

WGP_SCRIPT=$1

if [ -z $WGP_SCRIPT ]; then
	echo "Need to provide dir to script file on remote!"
	exit 1
fi

WGP_SSHLOGINS=$(dirname ${WGP_SCRIPT})"/sshlogins.txt"
WGP_PARAMINPUT=$(dirname ${WGP_SCRIPT})"/param-input.txt"

echo "Running script on remote: "$WGP_SCRIPT
echo "SSH file: "$WGP_SSHLOGINS

export WGP_SCRIPT

parallel -k \
--max-procs=$WGP_MAXPROC \
-a $WGP_PARAMINPUT \
--colsep ' ' \
--no-notice \
--sshloginfile $WGP_SSHLOGINS \
--env WGP_SCRIPT \
$WGP_SCRIPT ::: {1} {2} {3}
